services:
  - type: background
    name: nats-server
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    ports:
      - port: 4222
        protocol: tcp
      - port: 8222
        protocol: tcp
      - port: 6222
        protocol: tcp 